### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by GoDzM4TT3O** [M3GABOY/Termux_url_opener_all_in_one_downloader#1]
Instead of running:

```bash
​mkdir bin
#Installing dependencies
pkg update -y && pkg install wget -y && pkg install python -y && pkg install ffmpeg -y
yes | pip install youtube-dl

#Installing the script
wget -P "./bin/" --no-check-certificate "https://raw.githubusercontent.com/M3GABOY/Termux_url_opener_all_in_one_downloader/master/termux-url-opener" 
chmod +x "./bin/termux-url-opener"
termux-setup-storage
```

Why not run:

```bash
​mkdir bin
# Install dependencies
pkg update -y && pkg install wget python ffmpeg -y
# Install youtube-dl with pip and don't ask user for confirmation
yes | pip install youtube-dl

# Download the script from this repository
wget -P "./bin/" --no-check-certificate "https://raw.githubusercontent.com/M3GABOY/Termux_url_opener_all_in_one_downloader/master/termux-url-opener" 
# Make the script executable
chmod +x "./bin/termux-url-opener"
# Setup external storage access on Termux
termux-setup-storage
```

Also, instead of running:
(This is an example but you get the idea)

```bash
if [ condition ]; then
    do-something
else if [ condition-two ]; then
    do-something-else
else
    error-command
fi
```

Use the code below:

```bash
[[ condition ]] && do-something || [[ condition-two ]] && do-something-else || error-command
```

**Comment by RossComputerGuy** [comment]
Also the shell script that is downloaded is a mess, a `case` statement would make things so much cleaner. And why in the current working directory's `.bin` folder? I think it should install to `$HOME/.bin/`.

**Comment by M3GABOY** [comment]
> Also the shell script that is downloaded is a mess, a `case` statement would make things so much cleaner. And why in the current working directory's `.bin` folder? I think it should install to `$HOME/.bin/`.

This script should be run in the default location (home folder of ternux), the folder that termux is launched

**Comment by RossComputerGuy** [comment]
Yeah, the location that I proposed is a subdirectory in the home folder.

**Comment by M3GABOY** [comment]
> Yeah, the location that I proposed is a subdirectory in the home folder.

Already fixed the installation location issue. Now the script can be run without changing the directory to the home folder
